apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - "ReadWriteMany"
  storageClassName: nfs
  nfs:
    path: /var/nfs/online-album-static/static
    server: harbor-slave3

