apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - image: registry.k8s.com/k8s/nginx:stable-perl
          name: nginx-test  
          ports:
          - containerPort: 80
            protocol: TCP
