apiVersion: v1
kind: Pod
metadata:
  name: mymaven
spec:
  containers:
  - image: registry.k8s.com/k8s/maven:3.6.3-openjdk-8
    name: mymaven-container
    lifecycle:
      postStart:
        exec:
          command: ["sh","./post-start-maven.sh"]
    volumeMounts:
    - mountPath: /static
      name: maven-static-resources
    workingDir: /static
    command: ["sh","./start-maven.sh"]
  volumes:
  - name: maven-static-resources
    hostPath:
      path: /export/data/k8s/online-album/online_album/static
      type: Directory
